# Generated by Django 5.0.3 on 2024-07-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_student_name_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='selectedCourses',
            field=models.ManyToManyField(blank=True, related_name='students', to='course.course'),
        ),
    ]
